---
- name: Configuracion de apache y Firewall
  hosts: webserver
  become: true
  tasks:
    - name: Install Apache
      yum:
        name: httpd
        state: present

    - name: Configuracion VirtualHost
      template:
        src: ../templates/vhost.conf.j2
        dest: /etc/httpd/conf.d/vhost.conf
      notify: Restart Apache

    - name: Asegurar trafico HTTP
      firewalld:
        service: http
        permanent: true
        state: enabled
      notify: Reload Firewall

    - name: Desplegar index.html
      template:
        src: ../templates/index.html.j2
        dest: /var/www/html/index.html

  
  handlers:
    - name: Restart Apache
      service:
        name: httpd
        state: restarted


    - name: Reload Firewall
      command: firewall-cmd --reload
